name: fishing_helper
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  permission_handler: ^11.0.0
  flutter:
    sdk: flutter
  countup: ^0.1.4
  hive: ^2.2.3
  uuid: ^4.0.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  open_filex: ^4.3.4
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  get_storage: ^2.1.1
  connectivity_plus: ^4.0.2
  firebase_storage: ^11.5.3
  rename_app: ^1.3.1

flutter_icons:
  image_path: "assets/images/icon/app-icon.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.3+1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/png/

  uses-material-design: true

